"""add_role_to_users

Revision ID: 5caccfa1a0b7
Revises: 77e2358a8d84
Create Date: 2026-07-21 13:24:40.344445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5caccfa1a0b7'
down_revision: Union[str, None] = '77e2358a8d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET role = 'user'")
    op.execute("UPDATE users SET role = 'super_admin' WHERE is_superuser = true")
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
